#!/bin/bash

#The script expects to have superuser rights

dnf install -y tomcat

mkdir /usr/share/tomcat/webapps/ROOT
echo "Hi M!" > /usr/share/tomcat/webapps/ROOT/index.html

systemctl start tomcat


### Test generated by AI ###

# Define URL and target string
URL="http://localhost:8080"
TARGET_STRING="Hi M!"

# Run curl and capture BOTH the HTTP status code and the page body
RESPONSE_FILE=$(mktemp)
HTTP_STATUS=$(curl -s -w "%{http_code}" -o "$RESPONSE_FILE" "$URL")

echo "Checking $URL..."
echo "-------------------------------------"
echo "Received HTTP Status Code: $HTTP_STATUS"

# Assume failure by default
PASSED=false

# Check condition 1: Status code must be 200
if [ "$HTTP_STATUS" -eq 200 ]; then
    echo "✅ Success: Status code is 200."
    
    # Check condition 2: String must exist in the body
    if grep -q "$TARGET_STRING" "$RESPONSE_FILE"; then
        echo "✅ Success: Page contains the string '$TARGET_STRING'."
        # Both conditions met! Flip the switch to true
        PASSED=true
    else
        echo "❌ Error: String '$TARGET_STRING' not found in the response body."
    fi
else
    echo "❌ Error: Expected status code 200, but got $HTTP_STATUS."
fi

# Clean up the temporary file
rm -f "$RESPONSE_FILE"

# Stop tomcat
systemctl start tomcat

# Final Verdict
echo "-------------------------------------"
if [ "$PASSED" = true ]; then
    echo "🎉 ALL CHECKS PASSED!"
    exit 0
else
    echo "🚨 CHECKS FAILED."
    exit 1
fi
