#!/bin/bash

#The script expects to have superuser rights

TOMCAT_PACKAGE="tomcat"

# If tomcat package name is different than "tomcat" e.g. "tomcat9"
if [[ -n "$1" && "$1" != "tomcat9" ]]; then
    echo "Error: Invalid option '$1'. Expected 'tomcat9'." >&2
    exit 1
fi

TOMCAT_PACKAGE="${1:-$TOMCAT_PACKAGE}"

dnf install -y ${TOMCAT_PACKAGE}

mkdir -p /usr/share/tomcat/webapps/ROOT
echo "Hi M!" > /usr/share/tomcat/webapps/ROOT/index.html

systemctl start tomcat
sleep 5

### Test, generated by AI ###

# Define URL and target string
URL="http://localhost:8080"
TARGET_STRING="Hi M!"

# Run curl and capture BOTH the HTTP status code and the page body
RESPONSE_FILE=$(mktemp)
HTTP_STATUS=$(curl -s -w "%{http_code}" -o "$RESPONSE_FILE" "$URL")

echo "Checking $URL..."
echo "-------------------------------------"
echo "Received HTTP Status Code: $HTTP_STATUS"

# Assume failure by default
PASSED=false

# Check condition 1: Status code must be 200
if [ "$HTTP_STATUS" -eq 200 ]; then
    echo "✅ Success: Status code is 200."
    
    # Check condition 2: String must exist in the body
    if grep -q "$TARGET_STRING" "$RESPONSE_FILE"; then
        echo "✅ Success: Page contains the string '$TARGET_STRING'."
        # Both conditions met! Flip the switch to true
        PASSED=true
    else
        echo "❌ Error: String '$TARGET_STRING' not found in the response body."
    fi
else
    echo "❌ Error: Expected status code 200, but got $HTTP_STATUS."
fi

# Clean up the temporary file
rm -f "$RESPONSE_FILE"


### Check the tomcat logs, generated by AI ###

# --- CONFIGURATION ---
# Path to your Tomcat log file
LOG_FILE_PATTERN="/var/log/tomcat/catalina*.log"

# Patterns to search for (WARNING and SEVERE are standard Tomcat levels)
SEARCH_PATTERNS="WARNING|SEVERE|ERROR"
# ---------------------

# 1. Expand the wildcard into an array
FILES=($LOG_FILE_PATTERN)
FILE_COUNT=${#FILES[@]}

# Check if only one log file exists
if [ "$FILE_COUNT" -ne 1 ]; then
    echo "ERROR: Expected exactly 1 log file, but found $FILE_COUNT."
    exit 1
fi

if [ ! -f "${FILES[0]}" ]; then
    echo "ERROR: Tomcat log file not found at $LOG_FILE_PATTERN"
    exit 1
fi

LOG_FILE=${FILES[0]}

# 2. Count the number of matches
# -E enables extended regex, -i makes it case-insensitive, -c counts the lines
ERROR_COUNT=$(grep -E -i -c "$SEARCH_PATTERNS" "$LOG_FILE")

# 3. Determine the outcome
if [ "$ERROR_COUNT" -gt 0 ]; then
    echo "===================================================="
    echo "🚨 ERROR: Found $ERROR_COUNT warnings/errors in Tomcat log!"
    echo "Log File: $LOG_FILE"
    echo "===================================================="
    
    # Optional: Print the last 5 issues found for quick context
    echo -e "\n--- Last 5 issues found: ---"
    grep -E -i "$SEARCH_PATTERNS" "$LOG_FILE" | tail -n 5
    
    # Exit with a non-zero status code (useful for automation/cron jobs)
    exit 1
fi

# Stop tomcat
systemctl start tomcat

# Final Verdict
echo "-------------------------------------"
if [ "$PASSED" = true ]; then
    echo "🎉 ALL CHECKS PASSED!"
    exit 0
else
    echo "🚨 CHECKS FAILED."
    exit 1
fi
