#!/bin/bash

#Apply patches from tomcat.spec file (Generated by AI)
apply_spec_patches() {
    local spec_file="${1:-../tomcat.spec}"

    if [[ ! -f "$spec_file" ]]; then
        echo "Error: Cannot find spec file '$spec_file'."
        return 1
    fi

    local -A patch_files
    local line patch_id raw_patch_file bash_patch_file target_file strip_mode

    echo "=== Parsing $spec_file for Patch Definitions ==="

    # Step 1: Read the file to map "Patch<N>: <filename>"
    while IFS= read -r line; do
        if [[ "$line" =~ ^Patch([0-9]+):[[:space:]]*(.*)$ ]]; then
            patch_id="${BASH_REMATCH[1]}"
            raw_patch_file="${BASH_REMATCH[2]}"

            # Translate spec macros %{var_name} into bash variables ${VAR_NAME}
            # The \U in sed forces the matched group to uppercase
            bash_patch_file=$(echo "$raw_patch_file" | sed -E 's/%\{([^}]+)\}/\$\{\U\1\}/g')

            # Evaluate the string so bash expands ${NAME}, ${MAJOR_VERSION}, etc.
            # NOTE: These variables MUST be defined in your script before calling this function!
            eval target_file="\"$bash_patch_file\""

            patch_files["$patch_id"]="$target_file"
            echo "Registered Patch$patch_id -> $target_file"
        fi
    done < "$spec_file"

    echo -e "\n=== Applying Patches ==="

    # Step 2: Read the file again to find and execute "%patch -P<N> -p<M>"
    while IFS= read -r line; do
        if [[ "$line" =~ ^%patch[[:space:]] ]]; then

            # Extract the Patch ID (-P flag)
            if [[ "$line" =~ -P[[:space:]]*([0-9]+) ]]; then
                patch_id="${BASH_REMATCH[1]}"
            else
                continue
            fi

            # Extract the strip mode (-p flag), default to 0
            strip_mode=0
            if [[ "$line" =~ -p([0-9]+) ]]; then
                strip_mode="${BASH_REMATCH[1]}"
            fi

            target_file="../${patch_files[$patch_id]}"

            if [[ -n "$target_file" ]]; then
                if [[ -f "$target_file" ]]; then
                    echo "-> Applying: $target_file (using -p$strip_mode)"

                    patch -p"$strip_mode" -i "$target_file" || {
                        echo "-> Error: Patching failed on $target_file"
                        return 2
                    }
                else
                    echo "-> Error: The file '$target_file' was not found on disk."
                    return 1
                fi
            else
                echo "-> Warning: '%patch' for P$patch_id found, but no 'Patch$patch_id: <file>' defined."
            fi
        fi
    done < "$spec_file"

    echo -e "\n=== Patching Complete ==="
    return 0
}

if [ "$#" -ne 1 ]; then
    echo "Error: Source package URL is required."
    echo "Usage: $0 <tomcat-src-rpm-link>"
    exit 1
fi

TOMCAT_LINK=$1
FILE_NAME="${TOMCAT_LINK##*/}"
NAME="tomcat"

echo "FILE_NAME: $FILE_NAME" 

if [[ "$FILE_NAME" =~ tomcat[0-9]*-([0-9]+)\.([0-9]+) ]]; then
    export MAJOR_VERSION="${BASH_REMATCH[1]}"
    export MINOR_VERSION="${BASH_REMATCH[2]}"

    echo "Successfully parsed versions:"
    echo "MAJOR_VERSION=$MAJOR_VERSION"
    echo "MINOR_VERSION=$MINOR_VERSION"
else
    echo "Error: Could not parse major and minor versions from $filename"
    exit 1
fi

mkdir tomcat
cd tomcat
dnf install -y ant ant-junit java-25-openjdk-devel patch

# Download source code
echo "Downloading ${TOMCAT_LINK}"
wget ${TOMCAT_LINK} -O tomcat.rpm

rpm2cpio tomcat.rpm | cpio -idmv

tar_found=false
zip_found=false

# 1. Check for the tar.gz file
for file in apache-tomcat-*-src.tar.gz; do
    if [ -f "$file" ]; then
        echo "Found tarball: $file. Extracting..."
        tar -xzvf "$file"
        tar_found=true
        break # Exit the loop after finding and extracting the first match
    fi
done

# 2. If no tarball was found, check for the zip file
if [ "$tar_found" = false ]; then
    for file in tomcat-*-src.zip; do
        if [ -f "$file" ]; then
            echo "Tarball not found, but found zip file: $file. Unzipping..."
            unzip "$file"
            zip_found=true
            break # Exit the loop after finding and unzipping the first match
        fi
    done
fi

# 3. If neither was found, report an error
if [ "$tar_found" = false ] && [ "$zip_found" = false ]; then
    echo "Error: Neither apache-tomcat-*-src.tar.gz nor tomcat-*-src.zip was found."
    exit 1
fi

cd apache-tomcat-*-src

if [[ -f "../tomcat.spec" ]]; then
    apply_spec_patches ../tomcat.spec
else
    apply_spec_patches ../tomcat9.spec
fi

sed -i "/execute.test.nio=/c\execute.test.nio=false" build.properties.default
sed -i "/execute.test.apr=/c\execute.test.apr=false" build.properties.default
sed -i -e 's/value="plain"/value="xml"/' -e 's/value=".txt"/value=".xml"/' build.xml
echo -e 'test.exclude=**/*Cipher*.java' >> build.properties.default


ant test | tee test.log
